plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id 'maven-publish'
}

version = '1.0.1'
group = 'com.donutsmp.addon'

repositories {
    mavenCentral()
    maven { url = 'https://maven.meteordevelopment.dev/releases' }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.5"
    mappings "org.quiltmc:quilt-mappings:1.21.5+build.1"
    modImplementation "net.fabricmc:fabric-loader:0.16.9"
    modImplementation "meteordevelopment:meteor-client:0.1.0+1.21.5"
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
